project:
  type: website
  output-dir: docs

website:
  title: "Project CREDIBLE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About and Contact
        menu:
          - href: about.qmd
            text: About the Project
          - href: contact.qmd
            text: People and Contact Information
      - text: Resources
        menu:
          - href: resources.qmd
            text: General Resources
          - href: cohort-2.qmd
            text: Cohort 2
          - href: tools-and-resources.qmd
            text: Tools and Resources
          - href: abc.qmd
            text: ABCs of Data

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
  pdf:
    pdf-engine: xelatex

editor: visual
