project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Project CREDIBLE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Educator Network
        menu:
          - href: class-2025-26.qmd
            text: 2025-26 Class
          - href: teacher-leaders.qmd
            text: Teacher Leaders
          - href: abc.qmd
            text: ABCs of Data
          - href: tools-and-resources.qmd
            text: Tools and Resources
      - href: news.qmd
        text: News & Events
      - href: get-involved.qmd
        text: Get Involved
      - href: contact.qmd
        text: Contact
  page-footer:
    left: |
      Funded by the National Science Foundation (Grant No. 2239152)
    center: |
      [Past Cohorts](cohort-1.qmd)
    right: |
      Â© 2025 Project CREDIBLE

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
  pdf:
    pdf-engine: xelatex

editor: visual
